from selenium import webdriver
from selenium.webdriver.common.by import By
import time
def like_save():
    like = driver.find_element("xpath",'/html/body/div[2]/div/div/div/div[2]/div/div/div[1]/div/div[3]/div/div/div/div/div[2]/div/article/div/div[2]/div/div/div[2]/section[1]/span[1]/button')
    like.click()
    time.sleep(2)
    save = driver.find_element("xpath",'/html/body/div[2]/div/div/div/div[2]/div/div/div[1]/div/div[3]/div/div/div/div/div[2]/div/article/div/div[2]/div/div/div[2]/section[1]/span[4]/div/div/button')
    save.click()
    time.sleep(2)
    comment = driver.find_element("xpath",'/html/body/div[2]/div/div/div/div[2]/div/div/div[1]/div/div[3]/div/div/div/div/div[2]/div/article/div/div[2]/div/div/div[2]/section[3]/div/form/textarea')
    comment.click()
    comment = driver.find_element("xpath",'/html/body/div[2]/div/div/div/div[2]/div/div/div[1]/div/div[3]/div/div/div/div/div[2]/div/article/div/div[2]/div/div/div[2]/section[3]/div/form/textarea')
    comment.click()
    comment.send_keys("awesome")
    time.sleep(2)
    post = driver.find_element("xpath",'/html/body/div[2]/div/div/div/div[2]/div/div/div[1]/div/div[3]/div/div/div/div/div[2]/div/article/div/div[2]/div/div/div[2]/section[3]/div/form/div[2]/div')
    post.click()
    time.sleep(5)
    return
driver=webdriver.Chrome()
driver.get("https://instagram.com")
time.sleep(2)
user_name=driver.find_element("name",'username')
user_name.send_keys('shusuka0012')
time.sleep(3)
password=driver.find_element("name",'password')
password.send_keys('cutestgirl@01')
time.sleep(1)
login=driver.find_element('xpath','/html/body/div[2]/div/div/div/div[1]/div/div/div/div[1]/section/main/article/div[2]/div[1]/div[2]/form/div/div[3]')
login.click()
time.sleep(10)

driver.get('https://www.instagram.com/explore/tags/puppydog/')
time.sleep(8)
select_post1=driver.find_element("xpath",'/html/body/div[2]/div/div/div/div[1]/div/div/div/div[1]/div[1]/div[2]/section/main/article/div[1]/div/div/div[1]/div[1]/a/div/div[2]')
select_post1.click()
time.sleep(5)
like_save()
next1=driver.find_element("xpath",'/html/body/div[2]/div/div/div/div[2]/div/div/div[1]/div/div[3]/div/div/div/div/div[1]/div/div/div/button')
next1.click()
time.sleep(5)
for num in range(5):
 like_save()
 next = driver.find_element("xpath",'/html/body/div[2]/div/div/div/div[2]/div/div/div[1]/div/div[3]/div/div/div/div/div[1]/div/div/div[2]/button')
 next.click()
 time.sleep(5)
driver.quit()
